### ISSUE TITLE
메인 메뉴 구성

### ISSUE THREAD

**Issue by computerfairy** [computerfairy/Managepersonalinfo#2]
[프로그램을 시작하면 동작하는 화면]

##Personal Informaiton Manage##

1. Contacts
2. To-do
3. Appointments
4. Exit

이렇게 만들려고 하는데 어떠신가요? 메뉴 구성은 한글로 하는것이 나으려나요??

**Comment by lutea67** [comment]
제가 메인메뉴 만들고 있었어요! user story에 쓴대로 영어로 해도 될것같아요
구성은

==============================
1. Contacts
2. To-do list
3. Appointments
4. 종료
=============================

이런식으로 구성하였습니다. 제목도 추가할게요!

**Comment by computerfairy** [comment]
넵 감사합니다^0^~~
